name: Node.js CI
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
              docker compose up -d --build --no-deps tuaf.vn
              docker ps -a
              docker system prune -a -f